// Auto-generated operation registry. Do not edit by hand.

export type OperationMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'

export interface OperationSpec {
  method: OperationMethod
  path: string
  service: string
  serverUrl: string | null
  pathParams: readonly string[]
  queryParams: readonly string[]
  requestSchema: string | null
  responseSchema: string | null
}

export const OPERATIONS = {
  "ConnectionsController_list": {
    method: "GET",
    path: "/api/v1/connections",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: ["pageToken","pageSize","type"],
    requestSchema: null,
    responseSchema: "ListConnectionsResponseDto",
  },
  "ContextCreatorsController_createLink": {
    method: "POST",
    path: "/api/v1/context/links",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "CreateLinkDto",
    responseSchema: "CreatedContextItemResponseDto",
  },
  "ContextCreatorsController_createNote": {
    method: "POST",
    path: "/api/v1/context/notes",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "CreateNoteDto",
    responseSchema: "CreatedContextItemResponseDto",
  },
  "ContextCreatorsController_createSavedQuery": {
    method: "POST",
    path: "/api/v1/context/saved-queries",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "CreateSavedQueryDto",
    responseSchema: "CreatedContextItemResponseDto",
  },
  "ContextFilesController_finalize": {
    method: "POST",
    path: "/api/v1/context/files/{uploadId}/finalize",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["uploadId"],
    queryParams: [],
    requestSchema: "FinalizeUploadDto",
    responseSchema: "FileUploadResourceDto",
  },
  "ContextFilesController_finalizeMany": {
    method: "POST",
    path: "/api/v1/context/files/finalize",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "BulkFinalizeDto",
    responseSchema: "BulkFinalizeResponseDto",
  },
  "ContextFilesController_get": {
    method: "GET",
    path: "/api/v1/context/files/{uploadId}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["uploadId"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "FileUploadResourceDto",
  },
  "ContextFilesController_list": {
    method: "GET",
    path: "/api/v1/context/files",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: ["pageToken","pageSize"],
    requestSchema: null,
    responseSchema: "ListFilesResponseDto",
  },
  "ContextFilesController_uploadFromUrl": {
    method: "POST",
    path: "/api/v1/context/files/uploadFromUrl",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "UploadFromUrlDto",
    responseSchema: "FileUploadResourceDto",
  },
  "ContextFilesController_uploadFromUrls": {
    method: "POST",
    path: "/api/v1/context/files/uploadFromUrls",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "BulkUploadFromUrlsDto",
    responseSchema: "BulkUploadFromUrlsResponseDto",
  },
  "ContextFilesController_uploadUrl": {
    method: "POST",
    path: "/api/v1/context/files/uploadUrl",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "UploadUrlDto",
    responseSchema: "UploadUrlResponseDto",
  },
  "ContextFilesController_uploadUrls": {
    method: "POST",
    path: "/api/v1/context/files/uploadUrls",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "BulkUploadUrlsDto",
    responseSchema: "BulkUploadUrlsResponseDto",
  },
  "ContextItemsController_delete": {
    method: "DELETE",
    path: "/api/v1/context/items/{uid}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["uid"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "DeleteContextItemResponseDto",
  },
  "ContextItemsController_get": {
    method: "GET",
    path: "/api/v1/context/items/{uid}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["uid"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "ContextItemDto",
  },
  "ContextItemsController_list": {
    method: "GET",
    path: "/api/v1/context/items",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: ["pageToken","pageSize","contextTypes","verificationStatuses","searchQuery","topics"],
    requestSchema: null,
    responseSchema: "ListContextItemsResponseDto",
  },
  "ContextItemsController_listValues": {
    method: "GET",
    path: "/api/v1/context/items/{uid}/values",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["uid"],
    queryParams: ["contextType","contentKeyPath","pageSize","offset","pageToken","searchQuery","dataPathPrefix"],
    requestSchema: null,
    responseSchema: "ListContextItemValuesResponseDto",
  },
  "ContextItemsController_lookup": {
    method: "POST",
    path: "/api/v1/context/items/lookup",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "LookupContextItemDto",
    responseSchema: "LookupContextItemResponseDto",
  },
  "ContextItemsController_update": {
    method: "PATCH",
    path: "/api/v1/context/items/{uid}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["uid"],
    queryParams: ["updateMask"],
    requestSchema: "UpdateContextItemDto",
    responseSchema: null,
  },
  "CustomContextItemsController_batchCreate": {
    method: "POST",
    path: "/api/v1/context/custom-items/batch",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "BatchCreateCustomContextItemsDto",
    responseSchema: "BatchCreateCustomContextItemsResponseDto",
  },
  "CustomContextItemsController_create": {
    method: "POST",
    path: "/api/v1/context/custom-items",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "CreateCustomContextItemDto",
    responseSchema: "CreatedCustomContextItemResponseDto",
  },
  "CustomContextItemsController_delete": {
    method: "DELETE",
    path: "/api/v1/context/custom-items/{uid}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["uid"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "DeleteContextItemResponseDto",
  },
  "CustomContextItemsController_get": {
    method: "GET",
    path: "/api/v1/context/custom-items/{uid}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["uid"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "ContextItemDto",
  },
  "CustomContextItemsController_list": {
    method: "GET",
    path: "/api/v1/context/custom-items",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: ["pageToken","pageSize","contextTypes","verificationStatuses","searchQuery","topics"],
    requestSchema: null,
    responseSchema: "ListCustomContextItemsResponseDto",
  },
  "CustomContextItemsController_update": {
    method: "PATCH",
    path: "/api/v1/context/custom-items/{uid}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["uid"],
    queryParams: [],
    requestSchema: "UpdateCustomContextItemDto",
    responseSchema: null,
  },
  "EvaluationsController_getConfig": {
    method: "GET",
    path: "/api/v1/scopes/{id}/evaluations/config",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "EvaluationConfigDto",
  },
  "EvaluationsController_getRun": {
    method: "GET",
    path: "/api/v1/scopes/{id}/evaluations/runs/{runId}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id","runId"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "EvaluationRunWithResultsDto",
  },
  "EvaluationsController_listRuns": {
    method: "GET",
    path: "/api/v1/scopes/{id}/evaluations/runs",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: ["pageSize","pageToken"],
    requestSchema: null,
    responseSchema: "ListEvaluationRunsResponseDto",
  },
  "EvaluationsController_triggerRun": {
    method: "POST",
    path: "/api/v1/scopes/{id}/evaluations/runs",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "TriggerEvaluationRunResponseDto",
  },
  "EvaluationsController_updateConfig": {
    method: "PUT",
    path: "/api/v1/scopes/{id}/evaluations/config",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "UpdateEvaluationConfigDto",
    responseSchema: "EvaluationConfigDto",
  },
  "MemberGroupsController_list": {
    method: "GET",
    path: "/api/v1/users/member-groups",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: null,
    responseSchema: "ListMemberGroupsResponseDto",
  },
  "ModusChatController_chat": {
    method: "POST",
    path: "/api/v1/modus/chat",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "ModusChatRequestDto",
    responseSchema: "ModusChatResponseDto",
  },
  "ModusChatController_chatContinue": {
    method: "POST",
    path: "/api/v1/modus/conversations/{threadId}/chat",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["threadId"],
    queryParams: [],
    requestSchema: "ModusChatRequestDto",
    responseSchema: "ModusChatResponseDto",
  },
  "ModusContextController_compose": {
    method: "POST",
    path: "/api/v1/modus/context",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "ModusContextRequestDto",
    responseSchema: "ModusContextResponseDto",
  },
  "ModusConversationsController_get": {
    method: "GET",
    path: "/api/v1/modus/conversations/{threadId}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["threadId"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "ConversationDto",
  },
  "ModusConversationsController_list": {
    method: "GET",
    path: "/api/v1/modus/conversations",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: ["pageToken","page","pageSize","userId","toolName","source","timeframe","includeTools","kind"],
    requestSchema: null,
    responseSchema: "ListConversationsResponseDto",
  },
  "ModusRunsController_create": {
    method: "POST",
    path: "/agent/v1/modus/runs",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "ModusRunDto",
    responseSchema: null,
  },
  "OrgMembersController_list": {
    method: "GET",
    path: "/api/v1/users/org-members",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: null,
    responseSchema: "ListOrgMembersResponseDto",
  },
  "ResumeRunsController_create": {
    method: "POST",
    path: "/agent/v1/runs/{runId}/resume",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: ["runId"],
    queryParams: [],
    requestSchema: "ResumeRunDto",
    responseSchema: null,
  },
  "RunLifecycleController_active": {
    method: "GET",
    path: "/agent/v1/runs/active",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: [],
    queryParams: ["pageToken","pageSize"],
    requestSchema: null,
    responseSchema: "ActiveRunsResponseDto",
  },
  "RunLifecycleController_activeBySession": {
    method: "POST",
    path: "/agent/v1/runs/active-by-session",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "ActiveRunsBySessionDto",
    responseSchema: "ActiveRunsBySessionResponseDto",
  },
  "RunLifecycleController_cancel": {
    method: "POST",
    path: "/agent/v1/runs/{runId}/cancel",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: ["runId"],
    queryParams: [],
    requestSchema: "CancelRunDto",
    responseSchema: null,
  },
  "RunLifecycleController_editQueued": {
    method: "POST",
    path: "/agent/v1/runs/{runId}/queue-edit",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: ["runId"],
    queryParams: [],
    requestSchema: "EditQueuedRunDto",
    responseSchema: null,
  },
  "RunLifecycleController_events": {
    method: "GET",
    path: "/agent/v1/runs/{runId}/events",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: ["runId"],
    queryParams: [],
    requestSchema: null,
    responseSchema: null,
  },
  "RunLifecycleController_interrupt": {
    method: "POST",
    path: "/agent/v1/runs/{runId}/interrupt",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: ["runId"],
    queryParams: [],
    requestSchema: "InterruptRunDto",
    responseSchema: null,
  },
  "RunLifecycleController_stream": {
    method: "GET",
    path: "/agent/v1/runs/{runId}/stream",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: ["runId"],
    queryParams: [],
    requestSchema: null,
    responseSchema: null,
  },
  "ScopeChatController_chat": {
    method: "POST",
    path: "/api/v1/scopes/{id}/chat",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "SkillChatRequestDto",
    responseSchema: "SkillChatResponseDto",
  },
  "ScopeChatController_chatContinue": {
    method: "POST",
    path: "/api/v1/scopes/{id}/conversations/{threadId}/chat",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id","threadId"],
    queryParams: [],
    requestSchema: "SkillChatRequestDto",
    responseSchema: "SkillChatResponseDto",
  },
  "ScopeContextController_compose": {
    method: "POST",
    path: "/api/v1/scopes/{id}/context",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "ComposeSkillContextRequestDto",
    responseSchema: "ComposeSkillContextResponseDto",
  },
  "ScopeConversationsController_get": {
    method: "GET",
    path: "/api/v1/scopes/{id}/conversations/{threadId}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id","threadId"],
    queryParams: ["messageLimit","beforeMessageIndex"],
    requestSchema: null,
    responseSchema: "ConversationDto",
  },
  "ScopeConversationsController_list": {
    method: "GET",
    path: "/api/v1/scopes/{id}/conversations",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: ["pageToken","page","pageSize","userId","toolName","source","timeframe","includeTools"],
    requestSchema: null,
    responseSchema: "ListConversationsResponseDto",
  },
  "ScopeMemoriesController_delete": {
    method: "DELETE",
    path: "/api/v1/scopes/{id}/memories/{memoryId}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id","memoryId"],
    queryParams: [],
    requestSchema: null,
    responseSchema: null,
  },
  "ScopeMemoriesController_list": {
    method: "GET",
    path: "/api/v1/scopes/{id}/memories",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: ["pageToken","pageSize","userId","limit"],
    requestSchema: null,
    responseSchema: "ListMemoriesResponseDto",
  },
  "ScopeMemoriesController_search": {
    method: "POST",
    path: "/api/v1/scopes/{id}/memories/search",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "SearchMemoriesRequestDto",
    responseSchema: "ListMemoriesResponseDto",
  },
  "ScopeMemoriesController_update": {
    method: "PATCH",
    path: "/api/v1/scopes/{id}/memories/{memoryId}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id","memoryId"],
    queryParams: ["updateMask"],
    requestSchema: "UpdateMemoryRequestDto",
    responseSchema: null,
  },
  "ScopeRunsController_create": {
    method: "POST",
    path: "/agent/v1/scopes/{id}/runs",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "SkillRunDto",
    responseSchema: null,
  },
  "ScopeSupervisionController_get": {
    method: "GET",
    path: "/api/v1/scopes/{id}/supervision",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: ["view"],
    requestSchema: null,
    responseSchema: "SupervisionDto",
  },
  "ScopeSupervisionController_set": {
    method: "PUT",
    path: "/api/v1/scopes/{id}/supervision",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "SetSupervisionRequestDto",
    responseSchema: "SupervisionDto",
  },
  "ScopeSupervisionController_setActive": {
    method: "PUT",
    path: "/api/v1/scopes/{id}/supervision/active",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "SetSupervisionRequestDto",
    responseSchema: "SupervisionDto",
  },
  "ScopesController_acceptOwnershipTransfer": {
    method: "POST",
    path: "/api/v1/scopes/{id}/transfer-ownership/accept",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "ScopeDto",
  },
  "ScopesController_cancelOwnershipTransfer": {
    method: "DELETE",
    path: "/api/v1/scopes/{id}/transfer-ownership",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "ScopeDto",
  },
  "ScopesController_create": {
    method: "POST",
    path: "/api/v1/scopes",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "CreateSkillDto",
    responseSchema: "ScopeDto",
  },
  "ScopesController_delete": {
    method: "DELETE",
    path: "/api/v1/scopes/{id}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: null,
  },
  "ScopesController_deploy": {
    method: "POST",
    path: "/api/v1/scopes/{id}/deploy",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "DeploySkillDto",
    responseSchema: "DeployResponseDto",
  },
  "ScopesController_get": {
    method: "GET",
    path: "/api/v1/scopes/{id}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: ["view"],
    requestSchema: null,
    responseSchema: "ScopeDto",
  },
  "ScopesController_getVariation": {
    method: "GET",
    path: "/api/v1/scopes/{id}/variations/{variationUid}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id","variationUid"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "ScopeDto",
  },
  "ScopesController_list": {
    method: "GET",
    path: "/api/v1/scopes",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: ["pageToken","pageSize","view","search","managerId","includeVariation"],
    requestSchema: null,
    responseSchema: "ListSkillsResponseDto",
  },
  "ScopesController_patchMcpConfig": {
    method: "PATCH",
    path: "/api/v1/scopes/{id}/mcp-config",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "PatchSkillMcpConfigDto",
    responseSchema: "PatchSkillMcpConfigResponseDto",
  },
  "ScopesController_requestOwnershipTransfer": {
    method: "POST",
    path: "/api/v1/scopes/{id}/transfer-ownership",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "TransferOwnershipDto",
    responseSchema: "ScopeDto",
  },
  "ScopesController_restore": {
    method: "POST",
    path: "/api/v1/scopes/{id}/restore",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "ScopeDto",
  },
  "ScopesController_update": {
    method: "PATCH",
    path: "/api/v1/scopes/{id}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: ["updateMask"],
    requestSchema: "UpdateSkillDto",
    responseSchema: "ScopeDto",
  },
  "SuggestionsController_listApproved": {
    method: "GET",
    path: "/api/v1/suggestions/questions",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: ["pageToken","pageSize","scopeId","scopeIds"],
    requestSchema: null,
    responseSchema: "ListSuggestionQuestionsResponseDto",
  },
  "SuggestionsController_recordEvent": {
    method: "POST",
    path: "/api/v1/suggestions/questions/{id}/events",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "RecordSuggestionEventDto",
    responseSchema: null,
  },
  "ToolsController_list": {
    method: "GET",
    path: "/api/v1/tools",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: ["pageToken","pageSize"],
    requestSchema: null,
    responseSchema: "ListToolsResponseDto",
  },
  "UsageController_list": {
    method: "GET",
    path: "/api/v1/usage",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: ["since","until","rollup","model","group_by","skill_id","agent_id","user_id","interface","user_email"],
    requestSchema: null,
    responseSchema: "ListUsageResponseDto",
  },
  "UsageController_listUsers": {
    method: "GET",
    path: "/api/v1/usage/users",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: ["since","until"],
    requestSchema: null,
    responseSchema: "ListUsageUsersResponseDto",
  },
  "WorkflowActionsController_cancel": {
    method: "POST",
    path: "/agent/v1/workflow-actions/{runId}/cancel",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: ["runId"],
    queryParams: [],
    requestSchema: "CancelRunDto",
    responseSchema: null,
  },
  "WorkflowActionsController_execute": {
    method: "POST",
    path: "/agent/v1/workflow-actions",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "WorkflowActionDto",
    responseSchema: null,
  },
  "WorkflowInterfacesController_add": {
    method: "POST",
    path: "/api/v1/workflows/{id}/interfaces",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "AddAgentInterfaceDto",
    responseSchema: "AgentInterfaceDto",
  },
  "WorkflowInterfacesController_delete": {
    method: "DELETE",
    path: "/api/v1/workflows/{id}/interfaces/{interfaceId}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id","interfaceId"],
    queryParams: [],
    requestSchema: null,
    responseSchema: null,
  },
  "WorkflowInterfacesController_deleteAll": {
    method: "DELETE",
    path: "/api/v1/workflows/{id}/interfaces",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: null,
  },
  "WorkflowInterfacesController_list": {
    method: "GET",
    path: "/api/v1/workflows/{id}/interfaces",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "ListAgentInterfacesResponseDto",
  },
  "WorkflowInterfacesController_update": {
    method: "PATCH",
    path: "/api/v1/workflows/{id}/interfaces/{interfaceId}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id","interfaceId"],
    queryParams: ["updateMask"],
    requestSchema: "UpdateAgentInterfaceDto",
    responseSchema: "AgentInterfaceDto",
  },
  "WorkflowRunsController_create": {
    method: "POST",
    path: "/agent/v1/workflows/{id}/runs",
    service: "agent-service",
    serverUrl: "https://agent.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "AgentRunDto",
    responseSchema: null,
  },
  "WorkflowRunsController_get": {
    method: "GET",
    path: "/api/v1/workflows/{id}/runs/{runId}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id","runId"],
    queryParams: ["temporalRunId"],
    requestSchema: null,
    responseSchema: "GetAutomationRunResponseDto",
  },
  "WorkflowRunsController_list": {
    method: "GET",
    path: "/api/v1/workflows/{id}/runs",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: ["status","timeframe","approvalScope","search","pageSize","pageToken"],
    requestSchema: null,
    responseSchema: "ListAutomationRunsResponseDto",
  },
  "WorkflowsController_acceptOwnershipTransfer": {
    method: "POST",
    path: "/api/v1/workflows/{id}/transfer-ownership/accept",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "WorkflowDto",
  },
  "WorkflowsController_cancelOwnershipTransfer": {
    method: "DELETE",
    path: "/api/v1/workflows/{id}/transfer-ownership",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "WorkflowDto",
  },
  "WorkflowsController_create": {
    method: "POST",
    path: "/api/v1/workflows",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: [],
    requestSchema: "CreateAgentDto",
    responseSchema: "WorkflowDto",
  },
  "WorkflowsController_delete": {
    method: "DELETE",
    path: "/api/v1/workflows/{id}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: null,
  },
  "WorkflowsController_deploy": {
    method: "POST",
    path: "/api/v1/workflows/{id}/deploy",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "DeployAgentDto",
    responseSchema: "AgentDeployResponseDto",
  },
  "WorkflowsController_get": {
    method: "GET",
    path: "/api/v1/workflows/{id}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: ["view"],
    requestSchema: null,
    responseSchema: "WorkflowDto",
  },
  "WorkflowsController_list": {
    method: "GET",
    path: "/api/v1/workflows",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: [],
    queryParams: ["pageToken","pageSize","view","type","search","includeVariation"],
    requestSchema: null,
    responseSchema: "ListAgentsResponseDto",
  },
  "WorkflowsController_requestOwnershipTransfer": {
    method: "POST",
    path: "/api/v1/workflows/{id}/transfer-ownership",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "TransferOwnershipDto",
    responseSchema: "WorkflowDto",
  },
  "WorkflowsController_restore": {
    method: "POST",
    path: "/api/v1/workflows/{id}/restore",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: null,
    responseSchema: "WorkflowDto",
  },
  "WorkflowsController_toggle": {
    method: "POST",
    path: "/api/v1/workflows/{id}/toggle",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: [],
    requestSchema: "ToggleAgentDto",
    responseSchema: "WorkflowDto",
  },
  "WorkflowsController_update": {
    method: "PATCH",
    path: "/api/v1/workflows/{id}",
    service: "modus-api",
    serverUrl: "https://api.getmodus.com",
    pathParams: ["id"],
    queryParams: ["updateMask"],
    requestSchema: "UpdateAgentDto",
    responseSchema: "WorkflowDto",
  },
} as const satisfies Record<string, OperationSpec>

export type OperationId = keyof typeof OPERATIONS
