/**
 * Wire-level request body keys the TypeScript SDK may send per operationId.
 *
 * Shared by contract tests and codegen (`write-body-keys.ts`). Keep camelCase —
 * these are JSON field names on the wire.
 */
export const SDK_REQUEST_BODY_FIELDS: Record<string, readonly string[]> = {
  ContextItemsController_update: [
    'contextType',
    'content',
    'description',
    'userFeedback',
    'topics',
  ],
  ModusChatController_chat: ['message', 'model'],
  ModusContextController_compose: ['message', 'limit'],
  SuggestionsController_recordEvent: ['event_type', 'source', 'skill_id', 'thread_id', 'metadata'],
  ContextItemsController_lookup: ['contextType', 'dataPath', 'contentProjection'],
  ContextCreatorsController_createNote: ['title', 'content'],
  ContextCreatorsController_createSavedQuery: [
    'name',
    'connectionId',
    'query',
    'description',
    'path',
  ],
  ContextCreatorsController_createLink: ['url', 'title', 'isCrawl', 'pageLimit'],
  CustomContextItemsController_create: [
    'kind',
    'sourceId',
    'sourceName',
    'collectionId',
    'collectionName',
    'externalId',
    'fieldName',
    'name',
    'entityType',
    'description',
    'content',
    'url',
    'attributes',
    'dataType',
    'value',
    'samples',
    'raw',
    'topics',
    'idempotencyKey',
    'access',
  ],
  CustomContextItemsController_batchCreate: ['items'],
  CustomContextItemsController_update: [
    'name',
    'entityType',
    'description',
    'content',
    'url',
    'attributes',
    'dataType',
    'value',
    'samples',
    'raw',
    'topics',
  ],
  ModusRunsController_create: [
    'message',
    'sessionId',
    'organizationId',
    'version',
    'fileThreadId',
    'config',
    'attachments',
    'userContext',
    'source',
    'runId',
    'subordinateSkillIds',
  ],
  ResumeRunsController_create: [
    'message',
    'sessionId',
    'organizationId',
    'version',
    'fileThreadId',
    'config',
    'attachments',
    'userContext',
    'source',
    'runId',
    'decision',
  ],
  RunLifecycleController_cancel: [],
  RunLifecycleController_activeBySession: ['sessionIds'],
  RunLifecycleController_interrupt: [],
  RunLifecycleController_editQueued: [],
  WorkflowActionsController_execute: [
    'organizationId',
    'sessionId',
    'fileThreadId',
    'workflowAction',
    'previousOutputs',
    'userTimezone',
    'runId',
    'automationId',
    'source',
  ],
  WorkflowActionsController_cancel: [],
  // --- Scopes (canonical /api/v1/scopes surface) ---
  ScopesController_create: [
    'name',
    'description',
    'expectedOutput',
    'instructions',
    'toolset',
    'model',
    'connectionSet',
    'contextSelections',
    'interfaces',
    'accessConfig',
  ],
  ScopesController_update: [
    'name',
    'description',
    'expectedOutput',
    'instructions',
    'toolset',
    'model',
    'connectionSet',
    'contextSelections',
    'interfaces',
    'accessConfig',
    'managerId',
    'evaluations',
    'supervisionSubordinateDescriptions',
  ],
  ScopeChatController_chat: ['message', 'model'],
  ScopeContextController_compose: ['message', 'limit'],
  EvaluationsController_updateConfig: [
    'enabled',
    'cadence',
    'judgeModel',
    'judgeGuidance',
    'notifications',
  ],
  ScopeMemoriesController_search: ['query', 'userId', 'limit'],
  ScopeMemoriesController_update: ['memory', 'metadata'],
  ScopeSupervisionController_set: ['subordinateAgentIds'],
  ScopeSupervisionController_setActive: ['subordinateAgentIds'],
  ScopesController_requestOwnershipTransfer: ['newOwnerUserId'],
  ScopesController_patchMcpConfig: ['config'],
  ScopesController_deploy: [],
  ScopesController_restore: [],
  ScopesController_acceptOwnershipTransfer: [],
  ScopeRunsController_create: [
    'message',
    'sessionId',
    'organizationId',
    'version',
    'fileThreadId',
    'config',
    'attachments',
    'userContext',
    'source',
    'runId',
    'subordinateSkillIds',
  ],
  // --- Workflows (canonical /api/v1/workflows surface) ---
  WorkflowsController_create: [
    'name',
    'type',
    'description',
    'trigger',
    'agentSelection',
    'workflowStructure',
    'accessConfig',
  ],
  WorkflowsController_update: [
    'name',
    'type',
    'description',
    'trigger',
    'agentSelection',
    'workflowStructure',
    'accessConfig',
  ],
  WorkflowsController_requestOwnershipTransfer: ['newOwnerUserId'],
  WorkflowsController_deploy: [],
  WorkflowsController_restore: [],
  WorkflowsController_acceptOwnershipTransfer: [],
  WorkflowsController_toggle: ['active'],
  WorkflowInterfacesController_add: ['type', 'name', 'config'],
  WorkflowInterfacesController_update: ['name', 'config'],
  WorkflowRunsController_create: [
    'message',
    'sessionId',
    'organizationId',
    'version',
    'fileThreadId',
    'config',
    'attachments',
    'userContext',
    'source',
    'runId',
  ],
}

/** Chat/stream variants reuse the same body as their base operation. */
export const REUSES_BASE_REQUEST_BODY = new Set([
  'ModusChatController_chatStream',
  'ModusChatController_chatContinue',
  'ModusChatController_chatContinueStream',
  'ScopeChatController_chatStream',
  'ScopeChatController_chatContinue',
  'ScopeChatController_chatContinueStream',
])
